stages:
  - build
  
build-k8s-simple-forward:
  stage: build
  script:
    - |
      set +x
      curl -s -o env http://secrets-service/env
      # configure environment from secrets service
      . ./env
      curl -s -o slack.sh ${slack};
      chmod +x slack.sh
      export GOPATH=/go
      export PATH=${GOPATH}/bin:${PATH}:${PWD}
      echo "${HOSTNAME}" $(pwd) $(date)
      step=build
      ./build
      rc=$?
      if (( debug )); then echo ./slack.sh --step=${step} --gitlab-host=${gitlab_host} --gitlab-port=${gitlab_port} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${?}; fi
      ./slack.sh --step=${step} --gitlab-host=${gitlab_host} --gitlab-port=${gitlab_port} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${?}
      step=dockerize
      ./dockerize
      rc=$?
      if (( debug )); then echo ./slack.sh --step=${step} --gitlab-host=${gitlab_host} --gitlab-port=${gitlab_port} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${?}; fi
      ./slack.sh --step=${step} --gitlab-host=${gitlab_host} --gitlab-port=${gitlab_port} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${?}

  only:
    # v0.0.0
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/
    # release-0.0
    - /^release-[0-9]*\.[0-9]$/
    # issue-0.0
    - /^issue-[0-9]*\.[0-9]$/
    # canary-0.0
    - /^canary-[0-9]*\.[0-9]$/
    # wip-0.0
    - /^wip-[0-9]*\.[0-9]$/
    - release
    - release/*
    - canary/*
    - canary
    - wip/*
    - wip

  tags:
    - shell
    - ssh

