#!/bin/bash
dir=$(dirname $(readlink -f ${0}))
cd ${dir}
args="-s -w -X main.Build=$(date -u +%Y.%m.%d.%H.%M.%S) -X main.Commit=$(git log --format=%hash-%aI -n1)"
CGO_ENABLED=0 go build -a --tags netgo -ldflags "${args}" -o simple-forwarder simple-forwarder.go
