#!/bin/bash
dir=$(dirname $(readlink -f ${0}))
cd ${dir}
if go version|grep -q 1.4 ; then
    args="-s -w -X main.Build $(date -u +%Y.%m.%d.%H.%M.%S.%:::z) -X main.Commit $(git log --format=%hash-%aI -n1)"
fi
if go version|grep -q 1.5 ; then
    args="-s -w -X main.Build=$(date -u +%Y.%m.%d.%H.%M.%S.%:::z) -X main.Commit=$(git log --format=%hash-%aI -n1)"
fi
CGO_ENABLED=0 go build -a --tags netgo -ldflags "${args}" -o k8s-simple-forwarder k8s-simple-forwarder.go
