---
apiVersion: v1
kind: Secret
metadata:
  name: forwarder
  namespace: default
data:
  forwards.yaml: aHR0cC0wOgogIGRvd25zdHJlYW06ICIwLjAuMC4wOjg4ODkiCiAgdXBzdHJlYW06ICJuZ2lueC5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjgwIgpodHRwLTE6CiAgZG93bnN0cmVhbTogIjAuMC4wLjA6ODg5MCIKICB1cHN0cmVhbTogIm5naW54LmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6ODAiCnNzaC0wOgogIGRvd25zdHJlYW06ICIwLjAuMC4wOjI5MjAiCiAgdXBzdHJlYW06ICIwLjAuMC4wOjIyMjIiCnNzaC0xOgogIGRvd25zdHJlYW06ICIwLjAuMC4wOjI5MjEiCiAgdXBzdHJlYW06ICIwLjAuMC4wOjIyMjIiCnNzaC0yOgogIGRvd25zdHJlYW06ICIwLjAuMC4wOjI5MjIiCiAgdXBzdHJlYW06ICIwLjAuMC4wOjIyMjIiCnNzaC0zOgogIGRvd25zdHJlYW06ICIwLjAuMC4wOjI5MjMiCiAgdXBzdHJlYW06ICIwLjAuMC4wOjIyMjIiCgoKIyBzc2gtMDoKIyAgIGRvd25zdHJlYW06ICIwLjAuMC4wOjI5MjAiCiMgICB1cHN0cmVhbTogImdmcy0wOjIyMjIiCiMgc3NoLTE6CiMgICBkb3duc3RyZWFtOiAiMC4wLjAuMDoyOTIxIgojICAgdXBzdHJlYW06ICJnZnMtMToyMjIyIgojIHNzaC0yOgojICAgZG93bnN0cmVhbTogIjAuMC4wLjA6MjkyMiIKIyAgIHVwc3RyZWFtOiAiZ2ZzLTI6MjIyMiIKIyBzc2gtMzoKIyAgIGRvd25zdHJlYW06ICIwLjAuMC4wOjI5MjMiCiMgICB1cHN0cmVhbTogImdmcy0zOjIyMjIiCgojIyMjIyMjIyMjIC0gbmFtZTogaHR0cAojIyMjIyMjIyMjICAgZG93bnN0cmVhbTogIjAuMC4wLjA6ODg4OSIKIyMjIyMjIyMjIyAgIHVwc3RyZWFtOiAibmdpbng6ODAiCiMjIyMjIyMjIyMgLSBuYW1lOiBzc2gtMAojIyMjIyMjIyMjICAgZG93bnN0cmVhbTogIjAuMC4wLjA6MjkyMCIKIyMjIyMjIyMjIyAgIHVwc3RyZWFtOiAiZ2ZzLTA6MjIyMiIKIyMjIyMjIyMjIyAtIG5hbWU6IHNzaC0xCiMjIyMjIyMjIyMgICBkb3duc3RyZWFtOiAiMC4wLjAuMDoyOTIxIgojIyMjIyMjIyMjICAgdXBzdHJlYW06ICJnZnMtMDoyMjIyIgojIyMjIyMjIyMjIC0gbmFtZTogc3NoLTIKIyMjIyMjIyMjIyAgIGRvd25zdHJlYW06ICIwLjAuMC4wOjI5MjIiCiMjIyMjIyMjIyMgICB1cHN0cmVhbTogImdmcy0wOjIyMjIiCiMjIyMjIyMjIyMgLSBuYW1lOiBzc2gtMwojIyMjIyMjIyMjICAgZG93bnN0cmVhbTogIjAuMC4wLjA6MjkyMyIKIyMjIyMjIyMjIyAgIHVwc3RyZWFtOiAiZ2ZzLTA6MjIyMiIKCiMgY29uZmlnOgojIC0gbmFtZTogaHR0cAojICAgZG93bnN0cmVhbTogIjAuMC4wLjA6ODg4OSIKIyAgIHVwc3RyZWFtOiAibmdpbng6ODAiCiMgLSBuYW1lOiBzc2gtMAojICAgZG93bnN0cmVhbTogIjAuMC4wLjA6MjkyMCIKIyAgIHVwc3RyZWFtOiAiZ2ZzLTA6MjIyMiIKIyAtIG5hbWU6IHNzaC0xCiMgICBkb3duc3RyZWFtOiAiMC4wLjAuMDoyOTIxIgojICAgdXBzdHJlYW06ICJnZnMtMDoyMjIyIgojIC0gbmFtZTogc3NoLTIKIyAgIGRvd25zdHJlYW06ICIwLjAuMC4wOjI5MjIiCiMgICB1cHN0cmVhbTogImdmcy0wOjIyMjIiCiMgLSBuYW1lOiBzc2gtMwojICAgZG93bnN0cmVhbTogIjAuMC4wLjA6MjkyMyIKIyAgIHVwc3RyZWFtOiAiZ2ZzLTA6MjIyMiIK
  # resolv.conf: bmFtZXNlcnZlciAxMC4zLjAuMTAKbmFtZXNlcnZlciAxMC4wLjIuMwpzZWFyY2ggZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbCBzdmMuY2x1c3Rlci5sb2NhbCBjbHVzdGVyLmxvY2FsCm9wdGlvbnMgbmRvdHM6NQo=

---
# for versions before 1.8.0 use apps/v1beta1
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: forwarder
  # namespace: kube-system
  namespace: default
  labels:
    app: forwarder
spec:
  selector:
    matchLabels:
      name: forwarder
  template:
    metadata:
      labels:
        name: forwarder
    spec:
      containers:
      - name: forwarder
        image: davidwalter/forwarder:latest
        # imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        securityContext:
          privileged: true
        args:
        - "/forwarder"
        ## resources:
        ##   limits:
        ##     memory: 200Mi
        ##   requests:
        ##     cpu: 100m
        ##     memory: 200Mi
        volumeMounts:
        - name: config
          mountPath: /var/lib/forwarder
          readOnly: false
      volumes:
      - name: config
        secret:
          secretName: forwarder
          defaultMode: 420
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

# local variables:
# mode: yaml
# end:
