# for versions before 1.8.0 use apps/v1beta1
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: forwarder
  # namespace: kube-system
  namespace: default
  labels:
    app: forwarder
spec:
  selector:
    matchLabels:
      name: forwarder
  template:
    metadata:
      labels:
        name: forwarder
    spec:
      containers:
      - name: forwarder
        image: davidwalter/forwarder:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        args:
        - "/forwarder"
        - "0.0.0.0:8888"
        - "nginx.default:80"
        ## resources:
        ##   limits:
        ##     memory: 200Mi
        ##   requests:
        ##     cpu: 100m
        ##     memory: 200Mi
        volumeMounts:
        - name: var-lib-forwarder
          mountPath: /var/lib/forwarder
          readOnly: true
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      volumes:
      - name: var-lib-forwarder
        hostPath:
          path: /var/lib/forwarder
