#!/bin/bash
dir=$(dirname $(readlink -f ${0}))
cd ${dir}
. .version
cat > Dockerfile <<EOF
FROM centos:latest
COPY k8s-simple-forwarder /k8s-simple-forwarder
CMD [ "/k8s-simple-forwarder" ]
EOF

if docker build --force-rm --rm --tag=k8s-simple-forwarder . ; then
   docker tag k8s-simple-forwarder:latest k8s-simple-forwarder:${version}
fi
