dashboard:
  source: "0.0.0.0:8999"
  service: dashboard
  namespace: kube-system
  debug: true

echo:
  source: "0.0.0.0:8082"
  # sink: ":8888"
  sink: ":8081"
  debug: true

ssh:
  source: "strange:2200"
  # sink: ":8888"
  sink: "strange:22"
  debug: true

ssh2:
  source: "strange:2201"
  sink: "strange:22"
  debug: true
